export const estadosCidades: Record<string, { code: string; name: string; cidades: string[] }> = {
  'AC': { code: 'AC', name: 'Acre', cidades: ['Rio Branco', 'Cruzeiro do Sul', 'Sena Madureira'] },
  'AL': { code: 'AL', name: 'Alagoas', cidades: ['Maceió', 'Arapiraca', 'Rio Largo'] },
  'AP': { code: 'AP', name: 'Amapá', cidades: ['Macapá', 'Santana', 'Oiapoque'] },
  'AM': { code: 'AM', name: 'Amazonas', cidades: ['Manaus', 'Parintins', 'Itacoatiara'] },
  'BA': { code: 'BA', name: 'Bahia', cidades: ['Salvador', 'Feira de Santana', 'Vitória da Conquista', 'Camaçari', 'Lauro de Freitas'] },
  'CE': { code: 'CE', name: 'Ceará', cidades: ['Fortaleza', 'Caucaia', 'Juazeiro do Norte', 'Sobral'] },
  'DF': { code: 'DF', name: 'Distrito Federal', cidades: ['Brasília', 'Taguatinga', 'Ceilândia'] },
  'ES': { code: 'ES', name: 'Espírito Santo', cidades: ['Vitória', 'Vila Velha', 'Serra', 'Cariacica'] },
  'GO': { code: 'GO', name: 'Goiás', cidades: ['Goiânia', 'Aparecida de Goiânia', 'Anápolis', 'Rio Verde'] },
  'MA': { code: 'MA', name: 'Maranhão', cidades: ['São Luís', 'Imperatriz', 'Timon'] },
  'MT': { code: 'MT', name: 'Mato Grosso', cidades: ['Cuiabá', 'Várzea Grande', 'Rondonópolis', 'Lucas do Rio Verde'] },
  'MS': { code: 'MS', name: 'Mato Grosso do Sul', cidades: ['Campo Grande', 'Dourados', 'Três Lagoas'] },
  'MG': { code: 'MG', name: 'Minas Gerais', cidades: ['Belo Horizonte', 'Uberlândia', 'Contagem', 'Juiz de Fora', 'Betim', 'Montes Claros'] },
  'PA': { code: 'PA', name: 'Pará', cidades: ['Belém', 'Ananindeua', 'Santarém', 'Marabá'] },
  'PB': { code: 'PB', name: 'Paraíba', cidades: ['João Pessoa', 'Campina Grande', 'Santa Rita'] },
  'PR': { code: 'PR', name: 'Paraná', cidades: ['Curitiba', 'Londrina', 'Maringá', 'Ponta Grossa', 'Cascavel'] },
  'PE': { code: 'PE', name: 'Pernambuco', cidades: ['Recife', 'Jaboatão dos Guararapes', 'Olinda', 'Caruaru'] },
  'PI': { code: 'PI', name: 'Piauí', cidades: ['Teresina', 'Parnaíba', 'Picos'] },
  'RJ': { code: 'RJ', name: 'Rio de Janeiro', cidades: ['Rio de Janeiro', 'Niterói', 'Duque de Caxias', 'São Gonçalo', 'Teresópolis', 'Petrópolis'] },
  'RN': { code: 'RN', name: 'Rio Grande do Norte', cidades: ['Natal', 'Mossoró', 'Parnamirim'] },
  'RS': { code: 'RS', name: 'Rio Grande do Sul', cidades: ['Porto Alegre', 'Caxias do Sul', 'Pelotas', 'Santa Maria', 'Novo Hamburgo'] },
  'RO': { code: 'RO', name: 'Rondônia', cidades: ['Porto Velho', 'Ji-Paraná', 'Vilhena'] },
  'RR': { code: 'RR', name: 'Roraima', cidades: ['Boa Vista', 'Rorainópolis'] },
  'SC': { code: 'SC', name: 'Santa Catarina', cidades: ['Florianópolis', 'Joinville', 'Blumenau', 'Itajaí'] },
  'SP': { code: 'SP', name: 'São Paulo', cidades: ['São Paulo', 'Campinas', 'Santos', 'Sorocaba', 'Ribeirão Preto', 'Osasco', 'Guarulhos', 'São Bernardo do Campo'] },
  'SE': { code: 'SE', name: 'Sergipe', cidades: ['Aracaju', 'Nossa Senhora do Socorro', 'Lagarto'] },
  'TO': { code: 'TO', name: 'Tocantins', cidades: ['Palmas', 'Araguaína', 'Gurupi'] },
};
